// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('g:/Flutter/kapda-bazaar/node_modules/react');
var { Component } = React;
var ReactNative = require('g:/Flutter/kapda-bazaar/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('Kapda Bazaar', appParameters);
});
require('g:/Flutter/kapda-bazaar/index.js');